language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.x on Xenial Linux"
      python: 3.x           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.x on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.x running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
         #pip install -r requirements.txt # If you have a requirements.txt file, Travis CI runs
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 xcolors.py
